# check working example at 20250107 on git
from snakemake.utils import min_version
min_version("8.0")
import pandas as pd

configfile: "config/config.yaml"
container: "docker://rocker/tidyverse:4.5.1"

# input data
samples = pd.read_csv(config["sample_metadata"])["study_index"].tolist()

report: "report/workflow.rst"

rule all:
    input:
        expand("results/violin_plot/{sample}.png", sample=samples)

include: "rules/generate_data.smk"
include: "rules/histogram.smk"
include: "rules/scater_plot.smk"
include: "rules/vln_plot.smk"
