# check working example at 20250107 on git
from snakemake.utils import min_version
min_version("8.0")
import pandas as pd

configfile: "config/config.yaml"

# input data
samples = pd.read_csv(config["sample_metadata"])["study_index"].tolist()

report: "report/workflow.rst"

rule all:
    input:
        expand("results/plot/{sample}.png", sample=samples)

include: "rules/dwn_sif.smk"
include: "rules/generate_data.smk"
include: "rules/plot.smk"
include: "rules/wrangle.smk"
